context:
  version: "0.8"

package:
  name: ccache-storage-http-cpp
  version: ${{ version }}

source:
  url: https://github.com/ccache/ccache-storage-http-cpp/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 679bb7ad86183d55522cffcf495576a31459a5ce5cef804d71fbc63321a7416d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - zlib
    - libcurl
    - libuv

tests:
  - package_contents:
      bin:
        - ccache-storage-http
        - ccache-storage-https

about:
  homepage: https://github.com/ccache/ccache-storage-http-cpp
  summary: ccache HTTP(S) storage helper (C++)
  description: |
    ccache-storage-http-cpp is a ccache remote storage helper for HTTP/HTTPS,
    implemented in C++.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/ccache/ccache-storage-http-cpp

extra:
  recipe-maintainers:
    - traversaro
